spring:
  application:
    name: sopt-assignment

  datasource:
    url: jdbc:mysql://localhost:3306/assignment
    username: root
    password: Ghwn302412!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        # N+1 문제 해결: 전역 배치 사이즈 설정
        # 연관된 엔티티를 지정된 개수만큼 묶어서 IN 쿼리로 조회
        default_batch_fetch_size: 100
    show-sql: true

file:
  path:
    - "member.csv"